### ISSUE TITLE
SQL Update returns Cannot execute non idempotent command

### ISSUE THREAD

**Issue by SpareShade** [doctrine/orientdb-odm#188]
running  OrientDB Server v.2.0-M3 (build 0)

UPDATE person SET firstName = "Apollo" WHERE id = "816e40fb-1ffb-4e55-8b5b-f81031d4d007" 

returns:

com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute non idempotent command

any clues ??

**Comment by yon86** [comment]
answer is [here](https://groups.google.com/forum/#!topic/orient-database/-VBvFU2TfIw)
